# wow_rules.py
import re

# ==========================================
# 1. LE LEXIQUE (Injecté dans le cerveau de l'IA)
# ==========================================
WOW_LEXICON = {
    # --- Statistiques & Général WoW ---
    "Runestone Se": "Pierre runique Se",
    "Runestone": "Pierre runique",
    "stamina": "Endurance",
    "intellect": "Intelligence",
    "agility": "Agilité",
    "strength": "Force",
    "haste": "Hâte",
    "mastery": "Maîtrise",
    "critical strike": "Coup critique",
    "armor penetration": "Pénétration d'armure",
    "rating": "Score",
    "mana": "Mana",
    "health": "Points de vie",
    "drop": "Butin",
    "regalia": "Tenue de parade",
    "hit rating": "Score de toucher",
    "parry rating": "Score de parade",
    "block rating": "Score de blocage",
    "high-risk": "Haut-risque",
    "runestone": "Pierre runique",
    "runestones": "Pierres runiques",
    "expertise rating": "Score d'expertise",
    "dodge rating": "Score d'esquive",
    "resilience rating": "Score de résilience",
    "gnome": "Gnome",
    "deeprun tram": "Tram des profondeurs",
    "bonechewer": "Mâchoire-d'os",
    "screeching canyon": "Canyon des Chuintants",
    "mirage flats": "Salines",
    "broodlord lashlayer": "Seigneur des couvées Capesang",
    "lasherweave": "Tisse-flagellant",
    "felguard": "Gangregarde",
    "crag coyote": "Coyote des rochers",
    "shindigger stout": "Brune Casse-pattes",
    "pattern": "Patron",
    "dread magic": "Magie de l'effroi",
    "restless souls": "Âmes sans repos",
    "forsaken": "Réprouvés",
    "cult of the damned": "Culte des Damnés",
    "ironforge": "Forgefer",
    "tinker town": "Bricoleville",
    "wailing caverns": "Cavernes des Lamentations",
    "big game hunter": "Chasseur de gros gibier",
    "battlefield": "Champ de bataille",
    "darkshore": "Sombrivage",
    "hearthglen": "Âtreval",
    "blood furnace": "Fournaise du sang",
    "burning steppes": "Steppes Ardentes",
    "blackwing lair": "Repaire de l'Aile noire",
    "netherstorm": "Raz-de-Néant",
    "blade's edge": "Les Tranchantes",
    "underbog": "Basse-tourbière",
    "sunken temple": "Temple englouti",
    "razorfen kraul": "Kraal de Tranchebauge",
    "bluefen": "Bourbier Bleu",
    "blood knights": "Chevaliers de sang",
    "farstriders' square": "place des Pérégrins",
    "weapon master": "maître d'armes",
    "silvermoon": "Lune-d'Argent",
    "scarlet workers": "ouvriers écarlates",
    
    # --- Vocabulaire Précis WoW ---
    "skill": "Compétence",
    "ability": "Technique",
    "spell": "Sort",
    "spell power": "Puissance des sorts",
    "healing power": "Puissance des soins",
    "damage done": "Dégâts infligés",
    "healing done": "Soins prodigués",
    "damage over time": "Dégâts sur la durée",
    "auto attacks": "Attaques auto",
    "combo point finisher": "Coup de grâce",
    "clearcasting": "Idées claires",
    "crowd control": "Contrôle des foules",
    "radius": "Rayon",
    "stable master": "Maître des écuries",
    "hatchling": "Bébé",
    "crate": "Caisse",

    # --- Lore Officiel Blizzard ---
    "fel": "Gangrené",
    "death knight": "Chevalier de la mort",
    "warlock": "Démoniste",
    "lich king": "Roi-liche",
    "the lich king": "Le Roi-liche",
    "night elf": "Elfe de la nuit",
    "blood elf": "Elfe de sang",
    "draenei": "Draeneï",
    "father winter": "Grand-père Hiver",
    "wildkin": "Sélénien",
    "frostsaber": "Sabre-de-givre",
    "scourge": "Fléau",
    "undercity": "Fossoyeuse",
    "northrend": "Norfendre",
    "plaguelands": "Maleterres",
    "eastern plaguelands": "Maleterres de l'Est",
    "blackrock": "Rochenoire",
    "blackrock spire": "Pic Rochenoire",
    "lower blackrock spire": "Pic Rochenoire inférieur",
    "blackrock depths": "Profondeurs de Rochenoire",
    "molten core": "Cœur du Magma",
    "sunwell": "Puits de soleil",
    "thunder bluff": "Les Pitons du Tonnerre",
    "hellfire peninsula": "Péninsule des Flammes infernales",
    "dragonblight": "Désolation des dragons",
    "zangarmarsh": "Marécage de Zangar",
    "shadowfang keep": "Donjon d'Ombrecroc",
    "deadmines": "Mortemines",
    "stormwind": "Hurlevent",
    "scryer": "Clairvoyant",
    "dire maul": "Hache-Tripes",
    "dire maul east": "Hache-Tripes (Est)",
    "dire maul west": "Hache-Tripes (Ouest)",
    "dire maul north": "Hache-Tripes (Nord)",
    "grizzly hills": "Les Grisonnes",
    "dark portal": "La Porte des ténèbres",
    "blasted lands": "Terres Foudroyées",
    "outland": "Outreterre",
    "outlands": "Outreterre",
    "darkmoon faire": "Foire de Sombrelune",
    "bone wastes": "Désolation des Os",
    "stranglethorn vale": "Vallée de Strangleronce",
    "star\\'s rest": "Repos des étoiles",
    "star's rest": "Repos des étoiles",
    "graveyard": "Cimetière",

    # --- Serveur Ascension (Termes spécifiques) ---
    "worldforged": "Worldforged",
    "worldforged scroll": "Worldforged Scroll",
    "mystic enchant": "Enchant Mystique",
    "skill card": "Carte compétence",
    "talent essence": "Essence de talent",
    "ability essence": "Essence de compétence",
    "build": "Archétype",
    "build draft": "Archétype modèle",
    "draft mode": "Mode Draft",
    "classless": "Classless",
    "high-risk": "Haut-risque",
    "no-risk": "Sans-risque",
    "wildcard mode": "Mode hasard",
    "felforged": "Gangreforgé",
    "bloodforged": "Hémaforgé",
    "ironman": "Homme-de-fer",
    "heroic": "Héroïque",
    "mythic": "Mythique",
    "ascended": "Ascension",
    "nightmare mode": "Mode Cauchemar",
    "world boss": "Boss mondial",
    "world first": "Première mondiale",
    "realm first!": "Premier du royaume !",

    # --- Classes & Spécialisations (Conquest of Azeroth) ---
    "necromancer": "Nécromancien",
    "pyromancer": "Pyromancien",
    "cultist": "Cultiste",
    "starcaller": "Mande-étoiles",
    "sun cleric": "Clerc du soleil",
    "tinker": "Bricoleur", 
    "runemaster": "Maître des runes",
    "primalist": "Primaliste",
    "reaper": "Faucheur",
    "venomancer": "Vénomancien",
    "chronomancer": "Chronomancien",
    "bloodmage": "Mage de sang",
    "guardian": "Gardien",
    "stormbringer": "Porte-tempête",
    "felsworn": "Gangrelige",
    "barbarian": "Barbare",
    "witch doctor": "Sorcier-docteur",
    "witch hunter": "Chasseur de sorcières",
    "knight of xoroth": "Chevalier de Xoroth",
    "templar": "Templier",
    "ranger": "Forestier",

    # --- CC et Magie ---
    "stun": "Étourdissement",
    "stunned": "Étourdi",
    "root": "Immobilisé",
    "silence": "Réduit au silence",
    "frostfire": "Givrefeu",
    "hellfire": "Flammes infernales",
    "ley focus": "Concentration tellurique",
    "slag": "Scories",
    "ghastly": "Effroyable",

    # --- Protection des noms propres et devises serveur ---
    "fel power": "Fel Power",       # Devise Ascension — ne PAS traduire en "Gangrené"
    "felstone": "Felstone",          # NPC Jeremiah Felstone — nom propre, pas "Gangrené"
    "trainer": "Formateur",          # Évite "S'entraîner" comme nom de type NPC
    "cloth roll": "Rouleau de tissu", # Évite "Jet de dés de tissu"
    "nevermind": "Peu importe",
    "outstanding": "Excellent",
}

# ==========================================
# 2. LA DOUANE (Écrase les erreurs après l'IA)
# ==========================================
ERREURS_COMMUNES = {
    # Pronoms, Grammaire et bégaiements
    "Votre personnage": "vous",
    "votre personnage": "vous",
    "Votre Personnage": "vous",
    "de: la nature": "de la nature",
    "nos gobelins": "nous, les gobelins",
    "Renvois Retour": "renvoyés",
    "De: les Tués": "lors d'éliminations",
    "Butin De:": "butin de",
    "Suiv.": "suivante",
    "…": "...",
    "….": "...",
    "« ": '"', " »": '"', "«": '"', "»": '"',
    "De: ": "de ",
    "de: ": "de ",
    "De l'": "de l'",
    " Besoin": " besoin",
    " Sort ": " sort ",
    " Sorts ": " sorts ",
    " Classe ": " classe ",
    " Couleur": " couleur",
    " Spécial": " spécial",
    " Retoucher": " retoucher",
    " Jamais": " jamais",
    " Crier": " crier",
    " Monde": " monde",
    " Ennemi": " ennemi",
    " Tués": " tués",
    " Retour ": " retour ",
    "Vous Vous ": "Vous ",
    "Vous Vous": "Vous",
    "La Les ": "Les ",
    "La Le ": "Le ",
    "Source: ": "source ",
    "Si Si ": "Si ",
    "Vous Choisissez ": "Choisissez ",
    "Slay ": "Tuez ",
    "Cote\\32 ": "Score ",
    "Araignée de la Pesanteur Azur": "Araignée du Cauchemar azur",
    "Araña de la Pesadilla Azur": "Araignée du Cauchemar azur",
    "Forêt de Runestones": "Forêt des pierres runiques",
    "Runestones": "Pierres runiques",
    "rentrer à l'Accueil": "rentrer à la maison",
    "retour à l'Accueil": "rentrer à la maison",
    "Pas d’Échanger": "Pas d'échanges",
    "Rate de miss": "Chances de rater",
    "Bataille de champs": "Champ de bataille",
    "Grand Chasseur de Jeu": "Chasseur de gros gibier",
    "Grottes Lamentaires": "Cavernes des Lamentations",
    "Forgeferro": "Forgefer",
    "Bricoleurville": "Bricoleville",
    "ME VOUS DÉFIER?": "VOUS ME DÉFIEZ ?",
    "Horreaux": "Réprouvés",
    "Culte des Condamnés": "Culte des Damnés",
    "Je Aidez": "J'aide",
    "Je avait": "J'avais",
    "Terminé": "terminé",
    "Prêt": "prêt",
    "Toujours": "toujours",

    # === SÉCURITÉ : Interception des Hallucinations de l'IA ===
    "Okay, I understand. Please provide the English text you want me to translate. I will adhere strictly to your rules and instructions. I'm ready when you are": "Style classique",
    "Okay, I understand. I am ready. Bring on the English text. I will translate it into French, adhering strictly to your rules. begin!": "Ne revenez pas avant d’avoir réussi !",
    "Okay, I understand. I am ready. Bring on the English text. I will translate it into French, adhering strictly to your rules. begin! de Let!": "Ne revenez pas avant d’avoir réussi !",
    "Sure, here is the translation:": "",
    "Here is the translation:": "",
    "The translation is:": "",
    "I have translated the text:": "",
    "Note:": "",
    "Please note:": "",
    "As an AI,": "",
    "As an expert:": "",
    "I am an AI": "",
    "I cannot translate": "",
    "I couldn't translate": "",
    "In World of Warcraft,": "",
    
    # === ANTI-JUNK DATA (Ne pas traduire les chaînes dev/techniques) ===
    # Si le texte original ressemble à une variable interne ou un sort de test, on force le retour du texte tel quel en annulant la trad
    # (Ces regex seront gérées dans moteur_multilang.py, mais on met ici des purges si jamais l'IA tente de traduire)
    "Sort de test": "Test Spell",
    "Test de sort": "Spell Test",
    "Rechargé": "Reloaded",
    "Sort de développeur": "Dev Spell",
    "QA Test": "QA Test",
    "DO NOT USE": "DO NOT USE",
    "Ne pas utiliser": "DO NOT USE",
    "PH": "PH",
    "Placeholder": "Placeholder",
    "Espace réservé": "Placeholder",
    "Sort 375": "Spell 375",
    
    # === Traductions absurdes et littérales ===
    "Ventilateur Enragé": "Fanatique enragé",
    "Sanglier en rut": "Sanglier en stampede",
    "en train de tic-tac": "continue de tourner",
    "BRAS DE FER": "CASSER",
    "CausticWoW Sac Marin": "Vendeur de bourses de pièces CausticWoW",
    "Est de la chaumière brûlée": "Masure de l'Est incendiée",
    "Démande de Vertu": "Demoiselle de vertu",
    "Dungeon Diving: La Fonderie Sanguine": "Exploration de donjon : La Fournaise du sang",
    "Archétype puissant de: une liste d'Archétypes": "spécialisation puissante parmi une liste de builds",
    "Épaules du Contendeur": "Épaulières du prétendant",
    "Grade suivante:": "Rang suivant :",
    "Défaut:": "Défectueux :",
    
    # === Correction de la syntaxe et des objets ===
    "Équiper:": "Équipé :",
    "Boulons de Cuivre": "boulons en cuivre",
    "Colère Totem": "Totem de courroux",
    "Jet de dés pour les Techniques": "tirer des techniques",
    "Gardez la sécurité serrée": "Maintenez la sécurité renforcée",
    "Compétence en Herbalisme": "compétence en herboristerie",
    "Morts De: ": "Morts : ",
    "vient De: ": "vient de ",
    "Butin De:": "obtenu sur",

    # Écrasement des erreurs géographiques et Lore (Logs du 02-04)
    "Plaines Miroir": "Salines",
    "Canyon des Hurlements": "Canyon des Chuintants",
    "Coyote des Falaises Ancestral": "Ancien coyote des rochers",
    "Akim-Kurai Gangrené": "Gangregarde Akim-Kurai",
    "Clé de Magie Terrible": "Clé de magie de l'effroi",
    "Anneau des Âmes Agitées": "Anneau des âmes sans repos",
    "Robes de Lasherweave vaillantes": "Robes de tisse-flagellant valeureuses",
    
    # Corrections Métiers et Objets
    "Schéma: Doublures": "Patron : Doublures",
    "Schéma: ": "Patron : ",
    "Butin Épuisé": "Butin épuisé",
    "Alliance Druide": "Druide de l'Alliance",
    "Résurrection de Mort-vivant": "Mort-vivant ressuscité",

    # La maladie des raccourcis et des prépositions
    "De: les ": "des ",
    "De: la ": "de la ",
    "de: le ": "du ",
    "De: le ": "du ",
    "De: ": "de ",
    "Disp.": "Disponible",
    
    # Majuscules aléatoires de l'IA
    " Ami": " ami",
    " Contacts": " contacts",
    " Créature": " créature",
    " Créatures": " créatures",
    
    # Raccourcis et Franglais divers
    "Nain Brûlant": "Jeune dragonnet brûlant",
    "Chasseur Nain": "Chasseur Gnome",
    "Nain Paladin": "Paladin Gnome",
    "Ciel Gris Âne": "Âne de Ciel-gris",
    "Gangreforgé Acheter": "Achat Gangreforgé",
    "Pauldrons": "Épaulières",
    "Cannons": "Canons",
    "dans Flex": "en mode Flex",
    "en Flex": "en mode Flex",
    "Suivre les traceurs Retour": "Suivre les traceurs pour sortir",
    "Ya-six, Retour": "Ya-six, terminé",
    "d'Écailles de Fel": "en écailles gangrenées",

    # === Pronoms doublés manquants ===
    "Nous Nous ": "Nous ",
    "Nous Nous": "Nous",
    "Je Je ": "Je ",
    "Je Je": "Je",
    "Il Il ": "Il ",
    "Il Il": "Il",
    "Elle Elle ": "Elle ",
    "La La ": "La ",
    "La La": "La",

    # === Anglais résiduel après $B$B / $b$b ===
    "$B$BSoon,": "$B$BBientôt,",
    "$b$bSoon,": "$b$bBientôt,",
    "$B$BFinally ": "$B$BEnfin, ",
    "$b$bFinally ": "$b$bEnfin, ",
    "$B$BWhen ": "$B$BLorsque ",
    "$b$bWhen ": "$b$bLorsque ",
    "$B$BPlease ": "$B$BVeuillez ",
    "$b$bPlease ": "$b$bVeuillez ",
    "$B$BShe ": "$B$BElle ",
    "$b$bShe ": "$b$bElle ",
    "$B$BNeed ": "$B$BIl vous faut ",
    "$b$bNeed ": "$b$bIl vous faut ",
    "$B$BYears ": "$B$BDes années plus tard, ",
    "$b$bYears ": "$b$bDes années plus tard, ",
    "$B$BJump ": "$B$BSautez ",
    "$b$bJump ": "$b$bSautez ",
    "$B$BAwesome": "$B$BExcellent !",
    "$b$bAwesome": "$b$bExcellent !",
    "$B$BTrust ": "$B$BFaites confiance : ",
    "$b$bTrust ": "$b$bFaites confiance : ",
    "$B$BSo ": "$B$BAlors, ",
    "$b$bSo ": "$b$bAlors, ",
    "$B$BLast, ": "$B$B",
    "$b$bLast, ": "$b$b",
    "$B$BShould ": "$B$BSi ",
    "$b$bShould ": "$b$bSi ",
    "$B$BOnce ": "$B$BUne fois que ",
    "$b$bOnce ": "$b$bUne fois que ",
    "$B$BGo ": "$B$BAllez ",
    "$b$bGo ": "$b$bAllez ",

    # === Fix hybrides IA (mot anglais + traduction française collés) ===
    "By Par ": "Par ",
    "By par ": "par ",
    "As Vous ": "Vous ",
    "As vous ": "vous ",
    "Our les ": "Les ",
    "Our Nos ": "Nos ",
    "Rest je ": "Je ",
    "There a ": "Il y a ",

    # === Noms propres mal traduits ===
    "Jeremiah Gangrené": "Jeremiah Felstone",

    # Traductions littérales & Hallucinations
    "félin": "gangrené", "Félin": "Gangrené",
    "Chevalier-Mort": "Chevalier de la mort",
    "Coeur de Pierre": "Hardcore",
    "tavernes": "barres",
    "s'entraîne les faibles": "entraîne les faibles",
    "Parade Cote": "Score de parade",
    "Score de Précision": "Score de toucher",
    "Score de précision": "Score de toucher",
    "Carte de compétence": "Carte compétence",
    "Enchantement Mystique": "Enchant Mystique",
    "Homme de fer": "Homme-de-fer",
    "Mage de Sang": "Mage de sang",
    "Maulaire": "Hache-Tripes",
    "Maëlström (Ouest)": "Hache-Tripes (Ouest)",
    "Donjon des Supplices": "Hache-Tripes",
    "Terminé le défi": "Terminez le défi",
    "Regalia de": "Tenue de parade de",
    "Facile gagne, facile perd": "Ça va, ça vient",
    "pauvre chose": "le pauvre",
    "Pauvre chose": "La pauvre",
    "Que Terminé-vous": "Qu'avez-vous fait",
    "Vous l'avez Terminé": "Vous avez réussi",
    "c'est Terminé, alors": "c'est fait, alors",
    "Si Déjà connu": "Si utilisé",
    "L'Mana": "L'énergie",
    "l'Mana": "l'énergie",
    "Ce crate": "Cette caisse",
    "Bien usé tambour": "Tambour bien usé",
    "Arbuste de colonne": "Buisson d'épines",
    "Note publique invalide": "note invalide",
    "Mode Déterminée": "Mode Déterminé",
    "Pénétration de Sort": "Pénétration des sorts",
    "Archétype Brouillon": "Archétype modèle",
    "Gangreforgé Âme": "Âme gangreforgée",
    "\"vous récompensera\"": "vous récompensera",

    # === FIXES rapport 11-04-2026 ===

    # Fel Power mal traduit (devise Ascension)
    "Puissance gangrenée": "Fel Power",
    "puissance gangrenée": "Fel Power",
    "Puissance Gangrenée": "Fel Power",

    # Anglais résiduel
    "Slayez ": "Tuez ",
    "slayez ": "tuez ",

    # Notes et commentaires de l'IA dans la traduction
    "Lok'tar Ogar": "Lok'tar ogar",

    # Noms composés mal ordonnés
    "Vortex Ciel": "Vortex du ciel",
    "Berserk Amélioration": "Amélioration Berserk",
    "Amélioration de Berserk": "Amélioration Berserk",
    
    # Grammaire d'équipement et de Butins
    "de Kirin Tor": "du Kirin Tor",
    "des Combattants": "de combattant",
    "des Gladiateurs": "de gladiateur",
    "Peut avoir une chance": "A une chance",
    "trouvé comme Butin chez": "obtenu sur",
    "Butin à partir de": "obtenu sur",
    "tomber du": "être obtenu sur",
    "tomber de": "être obtenu sur",
    "Possède une chance de faire partie du Butin De: ": "A une chance d'être obtenu sur ",
    "Peut avoir une chance de tomber en Butin de ": "A une chance d'être obtenu sur ",
    "A chance to drop from ": "A une chance d'être obtenu sur ",
    
    # Noms de Boss, Lieux et Factions
    "Roi de la Liche": "Roi-liche",
    "Roi des Liches": "Roi-liche",
    "Roi Trône de Glace": "Roi-liche",
    "Roi Liche Déjà connu": "Roi-liche a utilisé",
    "Roi Liche": "Roi-liche",
    "Chercheur de Ténèbres": "Démoniste",
    "Noyau de Fusion": "Cœur du Magma",
    "Noyau de Lave": "Cœur du Magma",
    "Nain Druide du Sang": "Druide elfe de sang",
    "Nain druide": "Druide Elfe de sang",
    "Naine": "Elfe de la nuit",
    "Nain de Mûre": "Draeneï",
    "Père Noël": "Grand-père Hiver",
    "Joueur de 10 personnes": "10 joueurs",
    "Équipe de 10 Joueurs": "10 joueurs",
    "10 Joueur": "10 joueurs",
    "Repaire de l’Étoile": "Repos des étoiles",
    "Repaire de l'Étoile": "Repos des étoiles",
    " GY": " Cimetière",
    "GY du ": "Cimetière du ",
    "Anub'arak en Premier": "Anub'rekhan en Premier",
    "Nicheur": "Bricoleur",
    "Candele": "Bougie",
    "Horda": "Horde",
    "vengeanc.": "vengeance.",
    "dans la donjon": "dans le donjon",
    "Entrer dans la donjon": "Entrer dans le donjon",
    "Cooldowns de Soigneur": "Recharges du Soigneur",
    "Souleforge des morts": "Âme Felforgée",
    "Âme Forgée par les Felforgés": "Âme Felforgée",
    "Souppe": "Fléau",
    "Citadelle des Ombres": "Fossoyeuse",
    "Terres Fléuries": "Maleterres",
    "Basse-Épervierie": "Pic Rochenoire",
    "Tour noire": "Pic Rochenoire",
    "Jocker": "Joker",
    "Mode Nuit": "Mode Cauchemar",
    "Maître Krelthira stable": "Maître des écuries Krelthira",
    # À ajouter ou mettre à jour dans ERREURS_COMMUNES
 # --- Fix des Tags corrompus (vus dans Session 03-13-33) ---
    "$B $B": "$B$B",
    "$b$b": "$B$B",
    "$B$b": "$B$B",
    "$b $b": "$B$B",
    "$ N": "$N",
    "$ R": "$r",
    "$ C": "$c",
    
    # --- Fix Ponctuation et Caractères Spéciaux ---
    "“": "\"", # Remplace les guillemets "smart" par des droits
    "”": "\"",
    "‘": "'",
    "’": "'",
    "…": "...", # Normalisation des points de suspension
}

# ==========================================
# 3. REGEX : RÉPARATION DES BALISES ET STATS
# ==========================================
RESIDUS_POST_MARQUEUR = [
    (r'(\$[Bb]\$[Bb])Still,\s+', r'\1Cependant, '), 
    (r'(\$[Bb]\$[Bb])But\s+', r'\1Mais '),
    (r'(\$[Bb]\$[Bb])And\s+', r'\1Et '), 
    (r'(\$[Bb]\$[Bb])Even\s+', r'\1Même '),
    (r'(\$[Bb]\$[Bb])May\s+', r'\1Puisse '), 
    (r'(\$[Bb]\$[Bb])Instead,\s+', r'\1Au lieu de cela, '),
    (r'(\$[Bb]\$[Bb])Now,\s+', r'\1Maintenant, '), 
    (r'(\$[Bb]\$[Bb])However,\s+', r'\1Cependant, '),
    (r'(\$[Bb]\$[Bb])However[,.]?\s*', r'\1Cependant, '),
    (r'(\$[Bb]\$[Bb])Alright,\s+', r'\1Très bien, '), 
    (r'(\$[Bb]\$[Bb])Wait,\s+', r'\1Attends, '),
    (r'(\$[Bb]\$[Bb])Your\s+', r'\1Votre '), 
    (r'(\$[Bb]\$[Bb])For\s+', r'\1Car '),
    (r'(\$[Bb]\$[Bb])We\s+', r'\1Nous '), 
    (r'(\$[Bb]\$[Bb])You\s+', r'\1Vous '),
    (r'(\$[Bb]\$[Bb])I\s+', r'\1Je '), 
    (r'(\$[Bb]\$[Bb])It\s+', r'\1Il '),
    (r'(\$[Bb]\$[Bb])The\s+', r'\1La '), 
    (r'(\$[Bb]\$[Bb])Collect\s+', r'\1Collectez '),
    (r'(\$[Bb]\$[Bb])According\s+', r'\1Selon '), 
    (r'(\$[Bb]\$[Bb])Ready\s+', r'\1Prêt '),
    (r'(\$[Bb]\$[Bb])Inside\s+', r'\1En son sein, '), 
    (r'(\$[Bb]\$[Bb])Don\'t\s+', r'\1Ne '),
    (r'(\$[Bb]\$[Bb])Time\s+', r'\1Le temps '),
    (r'(\$[Bb]\$[Bb])This\s+', r'\1Ceci '),
    (r'(\$[Bb]\$[Bb])Look\s+', r'\1Regardez '),
    (r'(\$[Bb]\$[Bb])Prove\s+', r'\1Prouvez '),
    (r'(\$[Bb]\$[Bb])Few\s+', r'\1Peu '),
    (r'(\$[Bb]\$[Bb])If\s+', r'\1Si '),
    (r'(\$[Bb]\$[Bb])Let\s+', r'\1Laissez '),
    (r'(\$[Bb]\$[Bb])Delivering\s+', r'\1Livrant '),
    (r'(\$[Bb]\$[Bb])Something\s+', r'\1Quelque chose '),
    (r'(\$[Bb]\$[Bb])Very well,\s+', r'\1Très bien, '),
    (r'(\$[Bb]\$[Bb])Very\s+', r'\1Très '),
    (r'(\$[Bb]\$[Bb])Well\s+', r'\1Eh bien, '),
    (r'(\$[Bb]\$[Bb])While\s+', r'\1Bien que '),
    (r'(\$[Bb]\$[Bb])Interesting\s+', r'\1Intéressant '),
    (r'(\$[Bb]\$[Bb])The\s+', r'\1Le '),
    (r'(\$[Bb]\$[Bb])So\s+', r'\1Alors '),
    (r'(\$[Bb]\$[Bb])Do\s+', r'\1Avez-vous '),
    (r'(\$[Bb]\$[Bb])Overjoyed\s+', r'\1Aussi ravis '),
    (r'(\$[Bb]\$[Bb])I\'ll\s+', r'\1Je '),
    (r'(\$[Bb]\$[Bb])My\s+', r'\1Mes '),
    (r'(\$[Bb]\$[Bb])Making\s+', r'\1Fabriquer '),
    (r'(\$[Bb]\$[Bb])What\s+(?=[A-ZÉÀCe])', r'\1'),
    (r'(\$[Bb]\$[Bb])Here\s+sont\s+', r'\1Voici '),

    # === NOUVEAUX PATTERNS (identifiés dans les logs de session) ===
    (r'(\$[Bb]\$[Bb])Soon,\s+', r'\1Bientôt, '),
    (r'(\$[Bb]\$[Bb])Finally[,.]?\s+', r'\1Enfin, '),
    (r'(\$[Bb]\$[Bb])Once\s+', r'\1Une fois que '),
    (r'(\$[Bb]\$[Bb])When\s+', r'\1Lorsque '),
    (r'(\$[Bb]\$[Bb])Please\s+', r'\1Veuillez '),
    (r'(\$[Bb]\$[Bb])Should\s+', r'\1Si '),
    (r'(\$[Bb]\$[Bb])She\s+', r'\1Elle '),
    (r'(\$[Bb]\$[Bb])Go\s+(?=[A-ZÉÀ])', r'\1Allez '),
    (r'(\$[Bb]\$[Bb])Jump\s+', r'\1Sautez '),
    (r'(\$[Bb]\$[Bb])Need\s+', r'\1Il vous faut '),
    (r'(\$[Bb]\$[Bb])Years\s+', r'\1Des années plus tard, '),
    (r'(\$[Bb]\$[Bb])Trust\s+', r'\1Faites confiance : '),
    (r'(\$[Bb]\$[Bb])Last,\s+', r'\1'),  # Supprime le "Last," anglais orphelin
    (r'(\$[Bb]\$[Bb])Awesome[!,]?\s*', r'\1Excellent ! '),
    (r'(\$[Bb]\$[Bb])Commune\s+', r'\1Communiez '),
    (r'(\$[Bb]\$[Bb])Off\s+(?=[A-Z])', r'\1'),  # "Off the coast" → retire le mot orphelin
    (r'(\$[Bb]\$[Bb])Speak\s+', r'\1Parlez '),
    (r'(\$[Bb]\$[Bb])What\s+(?=[A-ZÉÀCQAa])', r'\1'),  # Efface le "What" qui traîne
]

STATS_FORMAT = [
    # Ordre des statistiques (Correction des inversions IA)
    (r'\bHâte Score\b', 'Score de Hâte'),
    (r'\bCoup critique Score\b', 'Score de coup critique'),
    (r'\bPénétration d\'armure Score\b', "Score de pénétration d'armure"),
    (r'\bParade Score\b', 'Score de Parade'),
    (r'\bTouche Score\b', 'Score de touche'),
    (r'\bDéfense Score\b', 'Score de défense'),
    (r'\bHâte Cote\b', 'Score de hâte'),
    (r'\bde Cote pour Coup critique\b', 'Score de coup critique'),
    (r'\bCote de Coup critique\b', 'Score de coup critique'),
    (r'\+(\d+)\s+aux Esprits\b', r'+\1 Esprit'),
    (r'\bSeize\s+(\d+)\b', r'Saisir \1'),

    (r'([-+]?\d+)\s+(Stamina|Intellect|Strength|Agility|Spirit|Endurance|Force|Agilité|Esprit|Intelligence)', r'+ \1 \2'),

    # Supprime l'espace français avant le symbole % (ex: "35 %" devient "35%")
    (r'(\d+)\s+%', r'\1%'),
    
    # Éradique le mot "Cote" pour les statistiques (ex: Cote d'Expertise -> Score d'expertise)
    (r"(?i)\bCote d'([Eé]xpertise|[Eé]squive)\b", r"Score d'\1"),
    (r"(?i)\bCote de (parade|hâte|blocage|toucher|coup critique|résilience|défense)\b", r"Score de \1"),
    
    # Supprime les virgules inventées avant le mot "dans"
    (r'(Vous ramène [àa] .*?),\s+dans\b', r'\1 dans'),
    (r'(obtenu sur\s+.*?),\s+dans\b', r'\1 dans'),

    # Répare la macro de pluriel Blizzard si l'IA a oublié le point-virgule (ex: |4seconde:secondes.)
    (r'(\|4[a-zA-Z]+:[a-zA-Z]+)([\s\.])', r'\1;\2'),
    
    # Sécurise les tags d'interface de difficulté
    (r'\[Risque Élevée?\]', r'[Haut-risque]'),

    # Remet de force les guillemets autour des défis, peu importe le verbe utilisé avant
    (r'([Dd]éfi)\s+(?!["«])(.*?)(?<!["»])\s+(en tant que|avec|en)\b', r'\1 "\2" \3'),
    
    # Restructuration grammaticale des équipements (Ex: du Kirin Tor de combattant -> de combattant du Kirin Tor)
    (r'(.+?)\s+du Kirin Tor de combattant\b', r'\1 de combattant du Kirin Tor'),
    
    # FIX DE L'ANGLAIS QUI SAIGNE (Ex: Khadgar's Robe -> Robe de Khadgar)
    (r"([A-Z][a-zA-Z]+)'s\s+(.+)", r"\2 de \1"),
    
    # Syntaxe répétitive de tes CSV
    (r'This ability is usable while shapeshifted', 'Cette technique peut être utilisée en étant transformé'),
    (r'Castable while moving', 'Utilisable en se déplaçant'),

    # === NOUVEAUX PATTERNS (identifiés dans les logs de session) ===

    # Fix "Fel Power" traduit en "Gangrené" par erreur (devise du serveur Ascension)
    (r'(\d+)\s+Gangrené\.', r'\1 Fel Power.'),
    (r'(\d+)\s+Gangrené\b', r'\1 Fel Power'),

    # Fix "Puissance gangrenée" → "Fel Power" dans les blocs de récompenses
    (r'(\d+)\s+Puissance\s+[Gg]angrenée\.?', r'\1 Fel Power'),

    # Suppression regex des notes IA résiduelles
    (r'\(Note\s*:[^)]{0,200}\)\.?', ''),
    (r'\(Remarque\s*:[^)]{0,200}\)\.?', ''),

    # Fix pronoms doublés résiduels (backup regex si ERREURS_COMMUNES ne les attrape pas)
    (r'\bNous Nous\b', 'Nous'),
    (r'\bJe Je\b', 'Je'),
    (r'\bIl Il\b', 'Il'),
    (r'\bElle Elle\b', 'Elle'),

    # Fix "De:" avec majuscule parasite (backup — ERREURS_COMMUNES gère la plupart)
    (r'\bDe:\s+([a-zA-ZéàèùâêîôûëïüÉÀÈ])', r'de \1'),

    # Fix "Orgrimmar Caisse" → "Caisse d'Orgrimmar" (nom + objet mal ordonnés)
    (r'\b([A-Z][a-zA-Zéèàùâêîôûë]+)\s+(Caisse|Baril)\b', r'\2 de \1'),

    # Fix "terminé le défi" → "Terminez le défi" (impératif manquant)
    (r'(?i)^terminé le défi', 'Terminez le défi'),
]